### ISSUE TITLE
Рефактор стилей кнопок и инпутов

### ISSUE THREAD

**Issue by LaProfessional** [LaProfessional/FilmHub#32]
# В компонентах Button.module.scss и Input.module.scss требуется приведение повторяющихся стилей к единым экземплярам

## Что нужно сделать

- Создать кнопки и инпуты, например, btnPrimary / btnSecondary / btnDanger / btnAccent и т.д... Избавится от дурацких названий
- Если стили повторяются, но размеры разные, необходимо применить mixin для настройки размеров, чтобы не повторять стили снова

**Вот как сейчас выглядит код для различных вариантов кнопок:**

```scss
.addCategoryBtn {
    border-radius: 0 .8rem .8rem 0;
    background-color: var(--button);

    padding: 0 1.3rem;

    transition: background-color .1s ease-in-out;

    cursor: pointer;

    &:hover {
        background-color: var(--button-hover);
    }
}

.regBtn {
    width: 100%;
    border-radius: .5rem;

    font-size: 1.4rem;
    font-weight: 500;
    color: var(--color-muted);

    padding: .6rem 1.2rem;

    cursor: pointer;

    &.active {
        background-color: var(--bg-primary);
        color: var(--color-primary);
    }
}

.logoutBtn {
    display: flex;
    align-items: center;
    gap: .6rem;
    width: 100%;

    @include text-styles.text-small-danger;

    padding: 1.4rem 1.4rem;

    &:hover {
        background-color: var(--bg-hover-primary);
    }
}

.headerButton {
    display: flex;
    justify-content: center;
    align-items: center;
    width: 40px;
    height: 38px;
    border-radius: 100%;
    padding: .8rem;
    transition: background-color .1s ease-in-out;

    &:hover {
        background-color: var(--bg-hover-primary);
    }
}

.btnLayoutControls {
    display: flex;
    justify-content: center;
    align-items: center;

    border-radius: .5rem;
    padding: .5rem;

    &:hover {
        background-color: var(--bg-hover-secondary);
    }

    &.active {
        background-color: var(--bg-accent);
    }
}

.btnFiltersControl {
    width: 100%;
    text-align: start;

    padding: 1rem 4.8rem 1rem 4.5rem;
}

.btnFilter {
    display: flex;
    width: 100%;
    min-width: 0;

    padding: 1rem 3.2rem 1rem 1.6rem;
}

.btnResetAll {
    display: flex;
    justify-content: center;
    align-items: center;
    gap: 1.2rem;
    width: 100%;
    max-height: 40px;

    @include text-styles.text-label-dark;

    border: 1px solid var(--border);
    border-radius: .5rem;
    background-color: var(--bg-accent);

    padding: 1rem 1.6rem;

    transition: background-color .2s ease;

    &:hover {
        background-color: var(--button-hover);
    }
}

.btnMore {
    display: flex;
    align-items: center;
    gap: .8rem;

    @include text-styles.text-small-muted-semibold;

    border-radius: .5rem;

    padding: 1rem .6rem;

    transition: all .2s ease;

    &:hover {
        background-color: var(--bg-hover-primary);

        color: var(--color-muted-hover);

        .iconEye {
            stroke: var(--color-muted-hover);
        }
    }

    .iconEye {
        stroke: var(--color-muted);
    }
}

.btnDeleteMovieCard,
.btnEditMovieCard {
    width: 28px;
    height: 28px;

    border-radius: .5rem;

    transition: all .2s ease;

    &:hover {
        background-color: var(--bg-hover-primary);
    }
}
```

**Не забывайте писать мне, уточнять, поскольку мог что-нибудь забыть. Пишите ваши идеи или улучшения.**
